markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: FightingLarry
author: "Larry"
email: 511573633@qq.com
name: "Fighting Larry"
url: http://www.iamlarry.com
domain: www.iamlarry.com
all_categories: [
["android", "Android开发","/posts/android.html"], 
["newtech", "Kotlin","/posts/newtech.html"],
["linux", "Linux相关","/posts/linux.html"],
["read", "读书笔记","/posts/read.html"], 
["other", "随手记","/posts/other.html"],
["about", "关于{{author}}","/about.html"]
]

paginate: 7
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
